// Regenerates phone/src/lib/icons.js from docs/ios/vibereel-iphone/icons/*.svg.
//   node phone/scripts/icons.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const dir = path.join(repo, 'docs/ios/vibereel-iphone/icons');
/* docs/ios/vibereel-iphone/icons/home.svg is corrupt (the bell's markup plus a
 * chunk of the gallery page pasted after it); the real glyph is the one the
 * screens' tab bars use. Overrides win over the file. */
const OVERRIDES = {
  home: { inner: '<path d="M4 10.5 12 4l8 6.5V19a1 1 0 0 1-1 1h-4.5v-6h-5v6H5a1 1 0 0 1-1-1z"></path>', fill: false }
};
const rows = [];
for (const f of fs.readdirSync(dir).filter((f) => f.endsWith('.svg')).sort()) {
  const s = fs.readFileSync(path.join(dir, f), 'utf8');
  const open = s.match(/<svg[^>]*>/)[0];
  const name = f.slice(0, -4);
  const start = s.indexOf(open) + open.length;
  const inner = OVERRIDES[name]?.inner ?? s.slice(start, s.indexOf('</svg>', start)).trim();
  const fill = OVERRIDES[name]?.fill ?? /fill="currentColor"/.test(open);
  rows.push(`  ${JSON.stringify(name)}: { svg: ${JSON.stringify(inner)}, fill: ${fill} },`);
}
const js = `/* The design's icon set (docs/ios/vibereel-iphone/icons/*.svg), as
 * { name: { svg: innerMarkup, fill: bool } }. 24 × 24 viewBox, drawn with the
 * .i class (stroke currentColor, 1.75). \`fill: true\` icons (play, pause) are
 * filled shapes — Icon.svelte adds .i--fill for them. Per-path stroke-width
 * overrides (the back-10/fwd-10 numerals) stay in the markup.
 * GENERATED by phone/scripts/icons.mjs — regenerate, don't hand-edit. */
export const ICONS = {
${rows.join('\n')}
};
`;
fs.writeFileSync(path.join(repo, 'phone/src/lib/icons.js'), js);
console.log(rows.length + ' icons');
